/**
 * This file is auto-generated by the Supabase CLI to reflect your database schema.
 * You can generate this file by running:
 *   npx supabase gen types typescript --project-id your-project-ref > src/lib/database.types.ts
 * 
 * Note: Replace 'your-project-ref' with your actual Supabase project reference.
 * Make sure to run this command after making any changes to your database schema.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your table types here
      // Example:
      // profiles: {
      //   Row: {
      //     id: string
      //     created_at: string
      //     updated_at: string
      //     username: string | null
      //     full_name: string | null
      //     avatar_url: string | null
      //   }
      //   Insert: {
      //     id?: string
      //     created_at?: string
      //     updated_at?: string
      //     username?: string | null
      //     full_name?: string | null
      //     avatar_url?: string | null
      //   }
      //   Update: {
      //     id?: string
      //     created_at?: string
      //     updated_at?: string
      //     username?: string | null
      //     full_name?: string | null
      //     avatar_url?: string | null
      //   }
      // }
    }
    Views: {
      // Add your view types here
    }
    Functions: {
      // Add your function types here
    }
    Enums: {
      // Add your enum types here
    }
    CompositeTypes: {
      // Add your composite type types here
    }
  }
}

// Helper type for table row types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']

// Helper type for table insert types
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']

// Helper type for table update types
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Helper type for view types
export type Views<T extends keyof Database['public']['Views']> = Database['public']['Views'][T]['Row']
